use std::cmp::Reverse;
use std::io::{self, Read, Write};
use std::net::IpAddr;
use std::path::Path;
use std::sync::RwLock;
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use reqwest::cookie::CookieStore;
use reqwest::header::HeaderValue;
use url::Url;

use crate::error::Result;

const COOKIE_FILE_HEADER: &str = "# Netscape HTTP Cookie File\n\
# https://curl.se/docs/http-cookies.html\n\
# This file was generated by libcurl! Edit at your own risk.\n\n";

#[derive(Debug, Default)]
pub struct CookieJar {
    cookies: RwLock<Vec<StoredCookie>>,
    explicit_cookie: RwLock<Option<String>>,
    explicit_cookie_origins: RwLock<Vec<CookieOrigin>>,
    explicit_cookie_unrestricted: RwLock<bool>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct StoredCookie {
    domain: String,
    include_subdomains: bool,
    path: String,
    secure: bool,
    expires: u64,
    name: String,
    value: String,
    http_only: bool,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct CookieOrigin {
    scheme: String,
    host: String,
    port: Option<u16>,
}

enum CookieUpdate {
    Set(StoredCookie),
    Delete {
        domain: String,
        path: String,
        name: String,
    },
}

impl CookieJar {
    pub fn set_explicit_cookie(&self, value: Option<&str>) {
        *self.explicit_cookie.write().expect("cookie jar lock") = value.map(ToString::to_string);
    }

    pub fn allow_explicit_cookie_for_url(&self, url: &Url, unrestricted: bool) {
        if unrestricted {
            *self
                .explicit_cookie_unrestricted
                .write()
                .expect("cookie jar lock") = true;
            return;
        }
        let Some(origin) = CookieOrigin::from_url(url) else {
            return;
        };
        let mut origins = self
            .explicit_cookie_origins
            .write()
            .expect("cookie jar lock");
        if !origins.contains(&origin) {
            origins.push(origin);
        }
    }

    pub fn load_from_inputs(&self, inputs: &[String], skip_session_cookies: bool) -> Result<()> {
        for input in inputs {
            self.load_from_input(input, skip_session_cookies)?;
        }
        Ok(())
    }

    pub fn load_response_inputs_for_url(
        &self,
        inputs: &[String],
        skip_session_cookies: bool,
        url: &Url,
    ) -> Result<()> {
        for input in inputs {
            self.load_response_input_for_url(input, skip_session_cookies, url)?;
        }
        Ok(())
    }

    fn load_from_input(&self, input: &str, skip_session_cookies: bool) -> Result<()> {
        if input.is_empty() {
            return Ok(());
        }

        let text = if input == "-" {
            let mut text = String::new();
            io::stdin().read_to_string(&mut text)?;
            text
        } else {
            let path = Path::new(input);
            if !path.is_file() {
                return Ok(());
            }
            std::fs::read_to_string(path)?
        };

        self.load_from_text(&text, skip_session_cookies);
        Ok(())
    }

    fn load_response_input_for_url(
        &self,
        input: &str,
        skip_session_cookies: bool,
        url: &Url,
    ) -> Result<()> {
        if input.is_empty() {
            return Ok(());
        }

        let text = if input == "-" {
            let mut text = String::new();
            io::stdin().read_to_string(&mut text)?;
            text
        } else {
            let path = Path::new(input);
            if !path.is_file() {
                return Ok(());
            }
            std::fs::read_to_string(path)?
        };

        self.load_response_text_for_url(&text, skip_session_cookies, url);
        Ok(())
    }

    pub fn save_to_path(&self, path: &Path, create_dirs: bool, verbose: bool) {
        if let Err(error) = self.try_save_to_path(path, create_dirs)
            && verbose
        {
            eprintln!(
                "WARNING: failed to save cookies in {}: {error}",
                path.display()
            );
        }
    }

    fn try_save_to_path(&self, path: &Path, create_dirs: bool) -> Result<()> {
        let text = self.to_netscape_file();
        if path == Path::new("-") {
            io::stdout().write_all(text.as_bytes())?;
            return Ok(());
        }

        if create_dirs
            && let Some(parent) = path
                .parent()
                .filter(|parent| !parent.as_os_str().is_empty())
        {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(path, text)?;
        Ok(())
    }

    fn load_from_text(&self, text: &str, skip_session_cookies: bool) {
        let now = unix_now();
        let mut cookies = self.cookies.write().expect("cookie jar lock");
        for line in text.lines() {
            let Some(cookie) = parse_cookie_file_line(line, now) else {
                continue;
            };
            if skip_session_cookies && cookie.expires == 0 {
                continue;
            }
            store_cookie(&mut cookies, cookie);
        }
    }

    fn load_response_text_for_url(&self, text: &str, skip_session_cookies: bool, url: &Url) {
        let now = unix_now();
        let mut cookies = self.cookies.write().expect("cookie jar lock");
        for line in text.lines() {
            let line = line.trim_end_matches('\r').trim_start();
            if line.trim_end().is_empty() || line.starts_with('#') {
                continue;
            }
            if let Some(cookie) = parse_netscape_cookie_line(line, false, now) {
                if !skip_session_cookies || cookie.expires != 0 {
                    store_cookie(&mut cookies, cookie);
                }
                continue;
            }
            let Some(value) = line
                .split_once(':')
                .and_then(|(name, value)| name.eq_ignore_ascii_case("set-cookie").then_some(value))
            else {
                continue;
            };
            let Some(update) = parse_set_cookie_file_for_url(value.trim(), url, now) else {
                continue;
            };
            apply_cookie_update(&mut cookies, update, skip_session_cookies);
        }
    }

    fn to_netscape_file(&self) -> String {
        let now = unix_now();
        let mut output = COOKIE_FILE_HEADER.to_string();
        let cookies = self.cookies.read().expect("cookie jar lock").clone();
        for cookie in cookies
            .iter()
            .filter(|cookie| cookie.expires == 0 || cookie.expires > now)
        {
            output.push_str(&cookie.netscape_line());
        }
        output
    }
}

fn parse_cookie_file_line(line: &str, now: u64) -> Option<StoredCookie> {
    let line = line.trim_end_matches('\r').trim_start();
    if line.trim_end().is_empty() {
        return None;
    }
    if let Some(line) = line.strip_prefix("#HttpOnly_") {
        return parse_netscape_cookie_line(line, true, now);
    }
    if line.starts_with('#') {
        return None;
    }
    if let Some(cookie) = parse_netscape_cookie_line(line, false, now) {
        return Some(cookie);
    }

    let value = line
        .split_once(':')
        .and_then(|(name, value)| name.eq_ignore_ascii_case("set-cookie").then_some(value))
        .unwrap_or(line);
    parse_set_cookie_file(value.trim(), now)
}

fn store_cookie(cookies: &mut Vec<StoredCookie>, cookie: StoredCookie) {
    cookies.retain(|existing| !existing.same_key(&cookie));
    cookies.push(cookie);
}

fn apply_cookie_update(
    cookies: &mut Vec<StoredCookie>,
    update: CookieUpdate,
    skip_session_cookies: bool,
) {
    match update {
        CookieUpdate::Set(cookie) => {
            if skip_session_cookies && cookie.expires == 0 {
                return;
            }
            store_cookie(cookies, cookie);
        }
        CookieUpdate::Delete { domain, path, name } => {
            cookies.retain(|existing| {
                existing.domain != domain || existing.path != path || existing.name != name
            });
        }
    }
}

fn parse_netscape_cookie_line(line: &str, http_only: bool, now: u64) -> Option<StoredCookie> {
    let mut fields = line.split('\t');
    let domain = fields.next()?.trim().to_ascii_lowercase();
    let include_subdomains = parse_cookie_bool(fields.next()?.trim())?;
    let path = fields.next()?.trim().to_string();
    let secure = parse_cookie_bool(fields.next()?.trim())?;
    let expires = fields.next()?.trim().parse::<u64>().ok()?;
    let name = fields.next()?.trim().to_string();
    let value = fields.next()?.trim().to_string();

    if domain.is_empty() || name.is_empty() || !path.starts_with('/') {
        return None;
    }
    if expires != 0 && expires <= now {
        return None;
    }

    Some(StoredCookie {
        domain,
        include_subdomains,
        path,
        secure,
        expires,
        name,
        value,
        http_only,
    })
}

fn parse_set_cookie_file(value: &str, now: u64) -> Option<StoredCookie> {
    let mut parts = value.split(';').map(str::trim);
    let (name, cookie_value) = parts.next()?.split_once('=')?;
    let name = trim_cookie_space(name);
    if name.is_empty() {
        return None;
    }

    let mut domain = None;
    let mut path = "/".to_string();
    let mut secure = false;
    let mut expires = 0;
    let mut http_only = false;
    let mut expired = false;

    for part in parts {
        let (attribute, raw_value) = part.split_once('=').unwrap_or((part, ""));
        match attribute.trim().to_ascii_lowercase().as_str() {
            "domain" => {
                let value = raw_value
                    .trim()
                    .trim_start_matches('.')
                    .to_ascii_lowercase();
                if !value.is_empty() {
                    domain = Some(format!(".{value}"));
                }
            }
            "path" => {
                let value = raw_value.trim().trim_matches('"');
                if value.starts_with('/') {
                    path = value.to_string();
                }
            }
            "max-age" => {
                if let Ok(value) = raw_value.trim().parse::<i64>() {
                    if value <= 0 {
                        expired = true;
                    } else {
                        expires = now.saturating_add(value as u64);
                    }
                }
            }
            "expires" => {
                if let Some(timestamp) = parse_expires(raw_value.trim()) {
                    if timestamp <= now {
                        expired = true;
                    } else {
                        expires = timestamp;
                    }
                }
            }
            "secure" => secure = true,
            "httponly" => http_only = true,
            _ => {}
        }
    }

    if expired {
        return None;
    }

    Some(StoredCookie {
        domain: domain?,
        include_subdomains: true,
        path,
        secure,
        expires,
        name: name.to_string(),
        value: trim_cookie_space(cookie_value).to_string(),
        http_only,
    })
}

fn parse_set_cookie_file_for_url(value: &str, url: &Url, now: u64) -> Option<CookieUpdate> {
    let mut parts = value.split(';').map(str::trim);
    let (name, cookie_value) = parts.next()?.split_once('=')?;
    let name = trim_cookie_space(name);
    if name.is_empty() {
        return None;
    }

    let host = url.host_str()?.to_ascii_lowercase();
    let mut domain = host.clone();
    let mut include_subdomains = false;
    let mut path = "/".to_string();
    let mut secure = false;
    let mut expires = 0;
    let mut http_only = false;
    let mut delete = false;

    for part in parts {
        let (attribute, raw_value) = part.split_once('=').unwrap_or((part, ""));
        match attribute.trim().to_ascii_lowercase().as_str() {
            "domain" => {
                let value = raw_value
                    .trim()
                    .trim_start_matches('.')
                    .to_ascii_lowercase();
                if !value.is_empty() {
                    if !domain_matches_source(&host, &value) {
                        return None;
                    }
                    domain = format!(".{value}");
                    include_subdomains = true;
                }
            }
            "path" => {
                let value = raw_value.trim().trim_matches('"');
                if value.starts_with('/') {
                    path = value.to_string();
                }
            }
            "max-age" => {
                if let Ok(value) = raw_value.trim().parse::<i64>() {
                    if value <= 0 {
                        delete = true;
                    } else {
                        expires = now.saturating_add(value as u64);
                    }
                }
            }
            "expires" => {
                if let Some(timestamp) = parse_expires(raw_value.trim()) {
                    if timestamp <= now {
                        delete = true;
                    } else {
                        expires = timestamp;
                    }
                }
            }
            "secure" => secure = true,
            "httponly" => http_only = true,
            _ => {}
        }
    }

    if delete {
        Some(CookieUpdate::Delete {
            domain,
            path,
            name: name.to_string(),
        })
    } else {
        Some(CookieUpdate::Set(StoredCookie {
            domain,
            include_subdomains,
            path,
            secure,
            expires,
            name: name.to_string(),
            value: trim_cookie_space(cookie_value).to_string(),
            http_only,
        }))
    }
}

fn parse_cookie_bool(value: &str) -> Option<bool> {
    match value.to_ascii_uppercase().as_str() {
        "TRUE" => Some(true),
        "FALSE" => Some(false),
        _ => None,
    }
}

impl CookieStore for CookieJar {
    fn set_cookies(&self, cookie_headers: &mut dyn Iterator<Item = &HeaderValue>, url: &Url) {
        let now = unix_now();
        let mut cookies = self.cookies.write().expect("cookie jar lock");
        for value in cookie_headers {
            let Ok(text) = value.to_str() else {
                continue;
            };
            let Some(update) = parse_set_cookie(text, url, now) else {
                continue;
            };
            match update {
                CookieUpdate::Set(cookie) => store_cookie(&mut cookies, cookie),
                CookieUpdate::Delete { domain, path, name } => {
                    cookies.retain(|existing| {
                        existing.domain != domain || existing.path != path || existing.name != name
                    });
                }
            }
        }
    }

    fn cookies(&self, url: &Url) -> Option<HeaderValue> {
        let now = unix_now();
        let mut cookies = self.cookies.write().expect("cookie jar lock");
        cookies.retain(|cookie| cookie.expires == 0 || cookie.expires > now);

        let mut matching_cookies = cookies
            .iter()
            .filter(|cookie| cookie.matches(url))
            .filter(|cookie| cookie.header_safe())
            .collect::<Vec<_>>();
        matching_cookies.sort_by_key(|cookie| {
            (
                Reverse(cookie.path.len()),
                Reverse(cookie.domain.len()),
                Reverse(cookie.name.len()),
            )
        });

        let mut header = matching_cookies
            .iter()
            .map(|cookie| format!("{}={}", cookie.name, cookie.value))
            .collect::<Vec<_>>()
            .join("; ");
        if let Some(explicit) = self
            .explicit_cookie
            .read()
            .expect("cookie jar lock")
            .as_deref()
            .filter(|explicit| !explicit.is_empty() && self.explicit_cookie_allowed(url))
        {
            if !header.is_empty() {
                header.push_str("; ");
            }
            header.push_str(explicit);
        }
        if header.is_empty() {
            None
        } else {
            HeaderValue::from_str(&header).ok()
        }
    }
}

impl CookieJar {
    fn explicit_cookie_allowed(&self, url: &Url) -> bool {
        if *self
            .explicit_cookie_unrestricted
            .read()
            .expect("cookie jar lock")
        {
            return true;
        }
        let Some(origin) = CookieOrigin::from_url(url) else {
            return false;
        };
        self.explicit_cookie_origins
            .read()
            .expect("cookie jar lock")
            .contains(&origin)
    }
}

impl CookieOrigin {
    fn from_url(url: &Url) -> Option<Self> {
        Some(Self {
            scheme: url.scheme().to_ascii_lowercase(),
            host: url.host_str()?.to_ascii_lowercase(),
            port: url.port_or_known_default(),
        })
    }
}

impl StoredCookie {
    fn same_key(&self, other: &StoredCookie) -> bool {
        self.domain == other.domain && self.path == other.path && self.name == other.name
    }

    fn matches(&self, url: &Url) -> bool {
        if self.secure && url.scheme() != "https" {
            return false;
        }
        let Some(host) = url.host_str().map(|host| host.to_ascii_lowercase()) else {
            return false;
        };
        let domain = self.domain.trim_start_matches('.').to_ascii_lowercase();
        let host_is_ip = host.parse::<IpAddr>().is_ok();
        let domain_matches = if host_is_ip {
            host == domain
        } else if self.include_subdomains {
            host == domain || host.ends_with(&format!(".{domain}"))
        } else {
            host == domain
        };
        domain_matches && path_matches(url.path(), &self.path)
    }

    fn header_safe(&self) -> bool {
        cookie_header_field_safe(&self.name) && cookie_header_field_safe(&self.value)
    }

    fn netscape_line(&self) -> String {
        let domain = if self.http_only {
            format!("#HttpOnly_{}", sanitize_field(&self.domain))
        } else {
            sanitize_field(&self.domain)
        };
        format!(
            "{domain}\t{}\t{}\t{}\t{}\t{}\t{}\n",
            bool_field(self.include_subdomains),
            sanitize_field(&self.path),
            bool_field(self.secure),
            self.expires,
            sanitize_field(&self.name),
            sanitize_field(&self.value)
        )
    }
}

fn parse_set_cookie(value: &str, url: &Url, now: u64) -> Option<CookieUpdate> {
    let mut parts = value.split(';').map(str::trim);
    let (name, cookie_value) = parts.next()?.split_once('=')?;
    let name = trim_cookie_space(name);
    if name.is_empty() {
        return None;
    }

    let host = url.host_str()?.to_ascii_lowercase();
    let mut domain = host.clone();
    let mut include_subdomains = false;
    let mut path = default_cookie_path(url);
    let mut secure = false;
    let mut expires = 0;
    let mut http_only = false;
    let mut delete = false;

    for part in parts {
        let (attribute, raw_value) = part.split_once('=').unwrap_or((part, ""));
        match attribute.trim().to_ascii_lowercase().as_str() {
            "domain" => {
                let value = raw_value
                    .trim()
                    .trim_start_matches('.')
                    .to_ascii_lowercase();
                if !value.is_empty() {
                    if !domain_matches_source(&host, &value) {
                        return None;
                    }
                    domain = format!(".{value}");
                    include_subdomains = true;
                }
            }
            "path" => {
                let value = raw_value.trim().trim_matches('"');
                if value.starts_with('/') {
                    path = value.to_string();
                }
            }
            "max-age" => {
                if let Ok(value) = raw_value.trim().parse::<i64>() {
                    if value <= 0 {
                        delete = true;
                    } else {
                        expires = now.saturating_add(value as u64);
                    }
                }
            }
            "expires" => {
                if let Some(timestamp) = parse_expires(raw_value.trim()) {
                    if timestamp <= now {
                        delete = true;
                    } else {
                        expires = timestamp;
                    }
                }
            }
            "secure" => secure = true,
            "httponly" => http_only = true,
            _ => {}
        }
    }

    if delete {
        Some(CookieUpdate::Delete {
            domain,
            path,
            name: name.to_string(),
        })
    } else {
        Some(CookieUpdate::Set(StoredCookie {
            domain,
            include_subdomains,
            path,
            secure,
            expires,
            name: name.to_string(),
            value: trim_cookie_space(cookie_value).to_string(),
            http_only,
        }))
    }
}

fn default_cookie_path(url: &Url) -> String {
    let path = url.path();
    if !path.starts_with('/') {
        return "/".to_string();
    }
    match path.rfind('/') {
        Some(0) | None => "/".to_string(),
        Some(index) => path[..index].to_string(),
    }
}

fn path_matches(request_path: &str, cookie_path: &str) -> bool {
    if cookie_path == "/" {
        return true;
    }
    request_path == cookie_path || request_path.starts_with(&format!("{cookie_path}/"))
}

fn domain_matches_source(host: &str, domain: &str) -> bool {
    if host.parse::<IpAddr>().is_ok() {
        host == domain
    } else {
        host == domain || host.ends_with(&format!(".{domain}"))
    }
}

fn parse_expires(value: &str) -> Option<u64> {
    httpdate::parse_http_date(value)
        .ok()?
        .duration_since(UNIX_EPOCH)
        .ok()
        .map(|duration| duration.as_secs())
}

fn unix_now() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or(Duration::ZERO)
        .as_secs()
}

fn bool_field(value: bool) -> &'static str {
    if value { "TRUE" } else { "FALSE" }
}

fn sanitize_field(value: &str) -> String {
    value
        .chars()
        .filter(|ch| !matches!(ch, '\t' | '\r' | '\n'))
        .collect()
}

fn cookie_header_field_safe(value: &str) -> bool {
    !value.bytes().any(|byte| byte <= 0x1f || byte == 0x7f)
}

fn trim_cookie_space(value: &str) -> &str {
    value.trim_matches(|ch| matches!(ch, ' ' | '\t'))
}

#[cfg(test)]
mod tests {
    use reqwest::header::HeaderValue;

    use super::*;

    #[test]
    fn stores_and_renders_basic_cookie() {
        let jar = CookieJar::default();
        let url = Url::parse("http://example.com/path/index.html").unwrap();
        let headers = [HeaderValue::from_static(
            "sid=abc; Domain=example.com; Path=/path; HttpOnly",
        )];

        jar.set_cookies(&mut headers.iter(), &url);

        let text = jar.to_netscape_file();
        assert!(text.contains("#HttpOnly_.example.com\tTRUE\t/path\tFALSE\t0\tsid\tabc\n"));
        assert_eq!(
            jar.cookies(&Url::parse("http://www.example.com/path/next").unwrap())
                .unwrap()
                .to_str()
                .unwrap(),
            "sid=abc"
        );
    }

    #[test]
    fn expired_cookie_deletes_existing_cookie() {
        let jar = CookieJar::default();
        let url = Url::parse("http://example.com/").unwrap();
        let headers = [HeaderValue::from_static("sid=abc; Path=/")];
        jar.set_cookies(&mut headers.iter(), &url);

        let headers = [HeaderValue::from_static("sid=gone; Path=/; Max-Age=0")];
        jar.set_cookies(&mut headers.iter(), &url);

        assert!(jar.cookies(&url).is_none());
        assert_eq!(jar.to_netscape_file(), COOKIE_FILE_HEADER);
    }

    #[test]
    fn rejects_cookie_for_unrelated_domain() {
        let jar = CookieJar::default();
        let url = Url::parse("http://example.com/").unwrap();
        let headers = [HeaderValue::from_static("sid=abc; Domain=evil.example")];

        jar.set_cookies(&mut headers.iter(), &url);

        assert_eq!(jar.to_netscape_file(), COOKIE_FILE_HEADER);
    }

    #[test]
    fn loads_netscape_cookie_file_lines() {
        let jar = CookieJar::default();

        jar.load_from_text("example.com\tFALSE\t/\tFALSE\t0\tsid\tabc\n", false);

        assert_eq!(
            jar.cookies(&Url::parse("http://example.com/").unwrap())
                .unwrap()
                .to_str()
                .unwrap(),
            "sid=abc"
        );
    }

    #[test]
    fn junk_session_cookie_loading_skips_session_cookies() {
        let jar = CookieJar::default();

        jar.load_from_text(
            "example.com\tFALSE\t/\tFALSE\t2000000000\tpersist\tyes\n\
             example.com\tFALSE\t/\tFALSE\t0\tsession\tno\n",
            true,
        );

        assert_eq!(
            jar.cookies(&Url::parse("http://example.com/").unwrap())
                .unwrap()
                .to_str()
                .unwrap(),
            "persist=yes"
        );
    }

    #[test]
    fn loads_set_cookie_file_lines_with_domains() {
        let jar = CookieJar::default();

        jar.load_from_text(
            "Set-Cookie: sid=abc; Domain=example.com; Path=/path; HttpOnly\n\
             Set-Cookie: hostless=ignored; Path=/\n",
            false,
        );

        assert_eq!(
            jar.cookies(&Url::parse("http://www.example.com/path/next").unwrap())
                .unwrap()
                .to_str()
                .unwrap(),
            "sid=abc"
        );
        assert_eq!(
            jar.to_netscape_file(),
            "# Netscape HTTP Cookie File\n\
             # https://curl.se/docs/http-cookies.html\n\
             # This file was generated by libcurl! Edit at your own risk.\n\n\
             #HttpOnly_.example.com\tTRUE\t/path\tFALSE\t0\tsid\tabc\n"
        );
    }

    #[test]
    fn loads_header_cookie_file_with_request_url_context() {
        let jar = CookieJar::default();
        let url = Url::parse("http://127.0.0.1/we/want/8").unwrap();
        jar.load_response_text_for_url(
            "HTTP/1.1 200 OK\n\
             Set-Cookie: foobar=name; domain=127.0.0.1; path=/;\n\
             Set-Cookie: mismatch=this; domain=127.0.0.1; path=\"/silly/\";\n\
             Set-Cookie: partmatch=present; domain=.0.0.1; path=/w;\n\
             Set-Cookie: cookie=yes; path=/we;\n\
             Set-Cookie: cookie=perhaps; path=/we/want;\n\
             Set-Cookie: name with space=is weird but; path=/we/want;\n\
             Set-Cookie: trailingspace    = removed; path=/we/want;\n\
             Set-Cookie: nocookie=yes; path=/WE;\n\
             Set-Cookie: blexp=yesyes; domain=127.0.0.1; domain=127.0.0.1; expiry=totally bad;\n\
             Set-Cookie: partialip=nono; domain=.0.0.1;\n\
             Set-Cookie: cookie1=\x01-junk\n\
             Set-Cookie: cookie9=junk--\t\n\
             Set-Cookie: cookie31=\x7f-junk\n",
            false,
            &url,
        );

        assert_eq!(
            jar.cookies(&url).unwrap().to_str().unwrap(),
            "name with space=is weird but; trailingspace=removed; cookie=perhaps; cookie=yes; foobar=name; blexp=yesyes; cookie9=junk--"
        );
    }

    #[test]
    fn appends_explicit_cookie_after_engine_cookies() {
        let jar = CookieJar::default();
        let url = Url::parse("http://example.com/").unwrap();
        jar.load_from_text("example.com\tFALSE\t/\tFALSE\t0\tsid\tabc\n", false);
        jar.set_explicit_cookie(Some("tool=curl"));
        jar.allow_explicit_cookie_for_url(&url, false);

        assert_eq!(
            jar.cookies(&url).unwrap().to_str().unwrap(),
            "sid=abc; tool=curl"
        );
    }

    #[test]
    fn explicit_cookie_is_scoped_to_allowed_origin() {
        let jar = CookieJar::default();
        let url = Url::parse("http://example.com:80/").unwrap();
        jar.set_explicit_cookie(Some("tool=curl"));
        jar.allow_explicit_cookie_for_url(&url, false);

        assert_eq!(jar.cookies(&url).unwrap().to_str().unwrap(), "tool=curl");
        assert!(
            jar.cookies(&Url::parse("http://example.com:81/").unwrap())
                .is_none()
        );
    }

    #[test]
    fn explicit_cookie_unrestricted_allows_other_origins() {
        let jar = CookieJar::default();
        jar.set_explicit_cookie(Some("tool=curl"));
        jar.allow_explicit_cookie_for_url(&Url::parse("http://example.com/").unwrap(), true);

        assert_eq!(
            jar.cookies(&Url::parse("http://other.example/").unwrap())
                .unwrap()
                .to_str()
                .unwrap(),
            "tool=curl"
        );
    }
}
