use std::fmt::Write as _;
use std::io::Write as _;
use std::path::Path;

use url::Url;

use crate::cli::{
    Config, ContinueAt, HttpVersionPreference, IpVersionPreference, SslVersionPreference,
    TransferConfig,
};
use crate::data::{self, PreparedBody};
use crate::error::{CurlError, Result};
use crate::{glob, ipfs, transfer};

pub fn write_source(path: &Path, config: &Config) -> Result<()> {
    let source = render_source(config)?;
    if path == Path::new("-") {
        let mut stdout = std::io::stdout().lock();
        stdout.write_all(source.as_bytes())?;
    } else {
        std::fs::write(path, source)?;
    }
    Ok(())
}

fn render_source(config: &Config) -> Result<String> {
    let render_transfers = prepare_transfers(config)?;
    let mut out = String::new();

    write_header(&mut out);
    write_declarations(&mut out, &render_transfers);
    write_slist_initializers(&mut out, &render_transfers);

    writeln!(out, "  curl = curl_easy_init();").unwrap();

    let mut request_index = 0;
    for transfer in &render_transfers {
        for url in &transfer.urls {
            if request_index > 0 {
                writeln!(out, "  curl_easy_reset(curl);").unwrap();
            }
            write_request(&mut out, transfer, url)?;
            request_index += 1;
        }
    }

    write_unrepresentable_comment(&mut out);
    writeln!(out, "  curl_easy_cleanup(curl);").unwrap();
    writeln!(out, "  curl = NULL;").unwrap();
    write_cleanup(&mut out, &render_transfers);
    out.push('\n');
    writeln!(out, "  return (int)result;").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out, "/**** End of sample code ****/").unwrap();

    Ok(out)
}

struct RenderTransfer<'a> {
    transfer: &'a TransferConfig,
    urls: Vec<String>,
    body: Option<PreparedBody>,
    headers: Vec<String>,
    slist: Option<String>,
    resolve_slist: Option<String>,
    connect_to_slist: Option<String>,
    mail_rcpt_slist: Option<String>,
    quote_slist: Option<String>,
    postquote_slist: Option<String>,
    prequote_slist: Option<String>,
}

fn prepare_transfers(config: &Config) -> Result<Vec<RenderTransfer<'_>>> {
    let mut slist_index = 1;
    let mut transfers = Vec::new();

    for transfer in &config.transfers {
        let query = data::prepare_body(&transfer.url_query)?;
        let body = data::prepare_body(&transfer.data)?;
        let urls = effective_urls(transfer, query.as_ref(), body.as_ref())?;
        let headers = effective_headers(transfer, body.as_ref())?;
        let slist = if headers.is_empty() {
            None
        } else {
            let name = format!("slist{slist_index}");
            slist_index += 1;
            Some(name)
        };
        let resolve_slist = if transfer.resolve.is_empty() {
            None
        } else {
            let name = format!("slist{slist_index}");
            slist_index += 1;
            Some(name)
        };
        let connect_to_slist = if transfer.connect_to.is_empty() {
            None
        } else {
            let name = format!("slist{slist_index}");
            slist_index += 1;
            Some(name)
        };
        let mail_rcpt_slist = if transfer.mail_rcpt.is_empty() {
            None
        } else {
            let name = format!("slist{slist_index}");
            slist_index += 1;
            Some(name)
        };
        let quote_slist = if transfer.ftp_quote.is_empty() {
            None
        } else {
            let name = format!("slist{slist_index}");
            slist_index += 1;
            Some(name)
        };
        let postquote_slist = if transfer.ftp_postquote.is_empty() {
            None
        } else {
            let name = format!("slist{slist_index}");
            slist_index += 1;
            Some(name)
        };
        let prequote_slist = if transfer.ftp_prequote.is_empty() {
            None
        } else {
            let name = format!("slist{slist_index}");
            slist_index += 1;
            Some(name)
        };

        transfers.push(RenderTransfer {
            transfer,
            urls,
            body,
            headers,
            slist,
            resolve_slist,
            connect_to_slist,
            mail_rcpt_slist,
            quote_slist,
            postquote_slist,
            prequote_slist,
        });
    }

    Ok(transfers)
}

fn write_header(out: &mut String) {
    out.push_str(
        "/********* Sample code generated by the curl command line tool **********\n\
 * All curl_easy_setopt() options are documented at:\n\
 * https://curl.se/libcurl/c/curl_easy_setopt.html\n\
 ************************************************************************/\n\
#include <curl/curl.h>\n\n\
int main(int argc, char *argv[])\n\
{\n\
  CURLcode result;\n\
  CURL *curl;\n",
    );
}

fn write_declarations(out: &mut String, transfers: &[RenderTransfer<'_>]) {
    for transfer in transfers {
        if let Some(slist) = &transfer.slist {
            writeln!(out, "  struct curl_slist *{slist};").unwrap();
        }
        if let Some(slist) = &transfer.resolve_slist {
            writeln!(out, "  struct curl_slist *{slist};").unwrap();
        }
        if let Some(slist) = &transfer.connect_to_slist {
            writeln!(out, "  struct curl_slist *{slist};").unwrap();
        }
        if let Some(slist) = &transfer.mail_rcpt_slist {
            writeln!(out, "  struct curl_slist *{slist};").unwrap();
        }
        if let Some(slist) = &transfer.quote_slist {
            writeln!(out, "  struct curl_slist *{slist};").unwrap();
        }
        if let Some(slist) = &transfer.postquote_slist {
            writeln!(out, "  struct curl_slist *{slist};").unwrap();
        }
        if let Some(slist) = &transfer.prequote_slist {
            writeln!(out, "  struct curl_slist *{slist};").unwrap();
        }
    }
    out.push('\n');
}

fn write_slist_initializers(out: &mut String, transfers: &[RenderTransfer<'_>]) {
    for transfer in transfers {
        write_slist_initializer(out, transfer.slist.as_deref(), &transfer.headers);
        write_slist_initializer(
            out,
            transfer.resolve_slist.as_deref(),
            &transfer.transfer.resolve,
        );
        write_slist_initializer(
            out,
            transfer.connect_to_slist.as_deref(),
            &transfer.transfer.connect_to,
        );
        write_slist_initializer(
            out,
            transfer.mail_rcpt_slist.as_deref(),
            &transfer.transfer.mail_rcpt,
        );
        write_slist_initializer(
            out,
            transfer.quote_slist.as_deref(),
            &transfer.transfer.ftp_quote,
        );
        write_slist_initializer(
            out,
            transfer.postquote_slist.as_deref(),
            &transfer.transfer.ftp_postquote,
        );
        write_slist_initializer(
            out,
            transfer.prequote_slist.as_deref(),
            &transfer.transfer.ftp_prequote,
        );
    }
}

fn write_request(out: &mut String, render: &RenderTransfer<'_>, url: &str) -> Result<()> {
    let transfer = render.transfer;
    emit_long_setopt(out, "CURLOPT_VERBOSE", 1);
    emit_long_setopt(out, "CURLOPT_BUFFERSIZE", 102400);
    emit_string_setopt(out, "CURLOPT_URL", url);

    if let Some(method) = &transfer.method {
        emit_string_setopt(out, "CURLOPT_CUSTOMREQUEST", method);
    }
    if let Some(target) = &transfer.request_target {
        emit_string_setopt(out, "CURLOPT_REQUEST_TARGET", target);
    }
    if transfer.disallow_username_in_url {
        emit_long_setopt(out, "CURLOPT_DISALLOW_USERNAME_IN_URL", 1);
    }
    if transfer.head {
        emit_long_setopt(out, "CURLOPT_NOBODY", 1);
    }
    if transfer.include_headers {
        emit_long_setopt(out, "CURLOPT_HEADER", 1);
    }
    if transfer.list_only {
        emit_long_setopt(out, "CURLOPT_DIRLISTONLY", 1);
    }
    if transfer.ftp_create_dirs {
        emit_raw_setopt(
            out,
            "CURLOPT_FTP_CREATE_MISSING_DIRS",
            "CURLFTP_CREATE_DIR_RETRY",
        );
    }
    if transfer.ftp_disable_epsv {
        emit_long_setopt(out, "CURLOPT_FTP_USE_EPSV", 0);
    }
    if let Some(skip_pasv_ip) = transfer.ftp_skip_pasv_ip {
        emit_long_setopt(
            out,
            "CURLOPT_FTP_SKIP_PASV_IP",
            if skip_pasv_ip { 1 } else { 0 },
        );
    }
    if let Some(slist) = &render.quote_slist {
        emit_raw_setopt(out, "CURLOPT_QUOTE", slist);
    }
    if let Some(slist) = &render.postquote_slist {
        emit_raw_setopt(out, "CURLOPT_POSTQUOTE", slist);
    }
    if let Some(slist) = &render.prequote_slist {
        emit_raw_setopt(out, "CURLOPT_PREQUOTE", slist);
    }
    if transfer.fail {
        emit_long_setopt(out, "CURLOPT_FAILONERROR", 1);
    }
    if let Some(slist) = &render.slist {
        emit_raw_setopt(out, "CURLOPT_HTTPHEADER", slist);
    }
    if let Some(mail_from) = &transfer.mail_from {
        emit_string_setopt(out, "CURLOPT_MAIL_FROM", mail_from);
    }
    if let Some(slist) = &render.mail_rcpt_slist {
        emit_raw_setopt(out, "CURLOPT_MAIL_RCPT", slist);
    }
    if let Some(slist) = &render.resolve_slist {
        emit_raw_setopt(out, "CURLOPT_RESOLVE", slist);
    }
    if let Some(slist) = &render.connect_to_slist {
        emit_raw_setopt(out, "CURLOPT_CONNECT_TO", slist);
    }
    if transfer.mail_rcpt_allowfails {
        emit_long_setopt(out, "CURLOPT_MAIL_RCPT_ALLOWFAILS", 1);
    }
    if let Some(blksize) = transfer.tftp_blksize {
        emit_long_setopt(out, "CURLOPT_TFTP_BLKSIZE", i64::from(blksize));
    }
    if transfer.tftp_no_options {
        emit_long_setopt(out, "CURLOPT_TFTP_NO_OPTIONS", 1);
    }
    if let Some(body) = &render.body
        && !transfer.get
    {
        emit_bytes_setopt(out, "CURLOPT_POSTFIELDS", &body.bytes);
        emit_raw_setopt(
            out,
            "CURLOPT_POSTFIELDSIZE_LARGE",
            &format!("(curl_off_t){}", body.bytes.len()),
        );
    }
    if let Some(upload_file) = &transfer.upload_file {
        emit_long_setopt(out, "CURLOPT_UPLOAD", 1);
        if transfer.ftp_append {
            emit_long_setopt(out, "CURLOPT_APPEND", 1);
        }
        if upload_file != "-"
            && let Ok(metadata) = std::fs::metadata(upload_file)
            && metadata.is_file()
        {
            emit_raw_setopt(
                out,
                "CURLOPT_INFILESIZE_LARGE",
                &format!("(curl_off_t){}", metadata.len()),
            );
        }
        writeln!(
            out,
            "  /* Upload source wiring is not yet represented by this Rust --libcurl slice. */"
        )
        .unwrap();
    }
    if !transfer.forms.is_empty() {
        writeln!(
            out,
            "  /* Multipart form generation is not yet represented by this Rust --libcurl slice. */"
        )
        .unwrap();
    }
    if let Some(user) = &transfer.user {
        emit_string_setopt(out, "CURLOPT_USERPWD", user);
        emit_raw_setopt(out, "CURLOPT_HTTPAUTH", "(long)CURLAUTH_BASIC");
    }
    if let Some(private_key) = &transfer.ssh_private_key {
        emit_path_setopt(out, "CURLOPT_SSH_PRIVATE_KEYFILE", private_key);
    }
    if let Some(public_key) = &transfer.ssh_public_key {
        emit_path_setopt(out, "CURLOPT_SSH_PUBLIC_KEYFILE", public_key);
    }
    if let Some(known_hosts) = &transfer.ssh_known_hosts {
        emit_path_setopt(out, "CURLOPT_SSH_KNOWNHOSTS", known_hosts);
    }
    if let Some(hostpubmd5) = &transfer.ssh_hostpubmd5 {
        emit_string_setopt(out, "CURLOPT_SSH_HOST_PUBLIC_KEY_MD5", hostpubmd5);
    }
    if let Some(hostpubsha256) = &transfer.ssh_hostpubsha256 {
        emit_string_setopt(out, "CURLOPT_SSH_HOST_PUBLIC_KEY_SHA256", hostpubsha256);
    }
    if transfer.compressed_ssh {
        emit_long_setopt(out, "CURLOPT_SSH_COMPRESSION", 1);
    }
    if let Some(token) = &transfer.oauth2_bearer {
        emit_string_setopt(out, "CURLOPT_XOAUTH2_BEARER", token);
    }
    if let Some(proxy) = &transfer.proxy {
        emit_string_setopt(out, "CURLOPT_PROXY", proxy);
    }
    if let Some(proxy_user) = &transfer.proxy_user {
        emit_string_setopt(out, "CURLOPT_PROXYUSERPWD", proxy_user);
    }
    if let Some(noproxy) = &transfer.noproxy {
        emit_string_setopt(out, "CURLOPT_NOPROXY", noproxy);
    }
    if transfer.insecure {
        emit_long_setopt(out, "CURLOPT_SSL_VERIFYPEER", 0);
        emit_long_setopt(out, "CURLOPT_SSL_VERIFYHOST", 0);
    }
    if let Some(timeout) = transfer.connect_timeout {
        emit_raw_setopt(
            out,
            "CURLOPT_CONNECTTIMEOUT_MS",
            &format!("{}L", timeout.as_millis()),
        );
    }
    if let Some(timeout) = transfer.max_time {
        emit_raw_setopt(
            out,
            "CURLOPT_TIMEOUT_MS",
            &format!("{}L", timeout.as_millis()),
        );
    }
    if let Some(max_filesize) = transfer.max_filesize {
        emit_raw_setopt(
            out,
            "CURLOPT_MAXFILESIZE_LARGE",
            &format!("(curl_off_t){max_filesize}"),
        );
    }
    if let Some(referer) = &transfer.referer {
        emit_string_setopt(out, "CURLOPT_REFERER", referer);
    }
    if transfer.auto_referer {
        emit_long_setopt(out, "CURLOPT_AUTOREFERER", 1);
    }
    if let Some(range) = &transfer.range {
        emit_string_setopt(out, "CURLOPT_RANGE", range);
    }
    if let Some(continue_at) = transfer.continue_at {
        match continue_at {
            ContinueAt::Offset(offset) => emit_raw_setopt(
                out,
                "CURLOPT_RESUME_FROM_LARGE",
                &format!("(curl_off_t){offset}"),
            ),
            ContinueAt::Auto => writeln!(
                out,
                "  /* --continue-at - depends on the selected output file size at runtime. */"
            )
            .unwrap(),
        }
    }
    if transfer.follow_location {
        emit_long_setopt(out, "CURLOPT_FOLLOWLOCATION", 1);
    }
    let postredir = postredir_bitmask(transfer);
    if postredir != 0 {
        emit_long_setopt(out, "CURLOPT_POSTREDIR", postredir);
    }
    if transfer.http09_allowed {
        emit_long_setopt(out, "CURLOPT_HTTP09_ALLOWED", 1);
    }
    emit_long_setopt(out, "CURLOPT_MAXREDIRS", transfer.max_redirs as i64);
    if let Some(cookie) = &transfer.cookie {
        emit_string_setopt(out, "CURLOPT_COOKIE", cookie);
    }
    for cookie_file in &transfer.cookie_files {
        emit_string_setopt(out, "CURLOPT_COOKIEFILE", cookie_file);
    }
    if let Some(cookie_jar) = &transfer.cookie_jar {
        emit_string_setopt(out, "CURLOPT_COOKIEJAR", &cookie_jar.to_string_lossy());
    }
    if transfer.junk_session_cookies {
        emit_long_setopt(out, "CURLOPT_COOKIESESSION", 1);
    }
    if transfer.compressed {
        emit_string_setopt(out, "CURLOPT_ACCEPT_ENCODING", "");
    }
    if let Some(user_agent) = &transfer.user_agent {
        emit_string_setopt(out, "CURLOPT_USERAGENT", user_agent);
    } else {
        emit_string_setopt(out, "CURLOPT_USERAGENT", &transfer::default_user_agent());
    }
    emit_http_version(out, transfer.http_version);
    emit_ssl_version(out, transfer.ssl_version);
    emit_ip_version(out, transfer.ip_version);
    emit_long_setopt(out, "CURLOPT_TCP_KEEPALIVE", 1);
    out.push('\n');
    writeln!(out, "  result = curl_easy_perform(curl);").unwrap();
    out.push('\n');
    Ok(())
}

fn write_unrepresentable_comment(out: &mut String) {
    out.push_str(
        "  /* Here is a list of options the curl code used that cannot get generated\n\
     as source easily. You may choose to either not use them or implement\n\
     them yourself.\n\n\
  CURLOPT_WRITEDATA was set to an object pointer\n\
  CURLOPT_WRITEFUNCTION was set to a function pointer\n\
  CURLOPT_HEADERFUNCTION was set to a function pointer\n\
  CURLOPT_HEADERDATA was set to an object pointer\n\
  CURLOPT_ERRORBUFFER was set to an object pointer\n\n\
  */\n\n",
    );
}

fn write_cleanup(out: &mut String, transfers: &[RenderTransfer<'_>]) {
    for transfer in transfers {
        if let Some(slist) = &transfer.slist {
            writeln!(out, "  curl_slist_free_all({slist});").unwrap();
            writeln!(out, "  {slist} = NULL;").unwrap();
        }
        if let Some(slist) = &transfer.resolve_slist {
            writeln!(out, "  curl_slist_free_all({slist});").unwrap();
            writeln!(out, "  {slist} = NULL;").unwrap();
        }
        if let Some(slist) = &transfer.connect_to_slist {
            writeln!(out, "  curl_slist_free_all({slist});").unwrap();
            writeln!(out, "  {slist} = NULL;").unwrap();
        }
        if let Some(slist) = &transfer.mail_rcpt_slist {
            writeln!(out, "  curl_slist_free_all({slist});").unwrap();
            writeln!(out, "  {slist} = NULL;").unwrap();
        }
        if let Some(slist) = &transfer.quote_slist {
            writeln!(out, "  curl_slist_free_all({slist});").unwrap();
            writeln!(out, "  {slist} = NULL;").unwrap();
        }
        if let Some(slist) = &transfer.postquote_slist {
            writeln!(out, "  curl_slist_free_all({slist});").unwrap();
            writeln!(out, "  {slist} = NULL;").unwrap();
        }
        if let Some(slist) = &transfer.prequote_slist {
            writeln!(out, "  curl_slist_free_all({slist});").unwrap();
            writeln!(out, "  {slist} = NULL;").unwrap();
        }
    }
}

fn effective_urls(
    transfer: &TransferConfig,
    query: Option<&PreparedBody>,
    body: Option<&PreparedBody>,
) -> Result<Vec<String>> {
    let mut urls = Vec::new();
    for (index, raw) in transfer.urls.iter().enumerate() {
        let raw = glob::apply_default_protocol(raw, transfer.proto_default.as_deref());
        let globoff =
            transfer.globoff || transfer.url_globoffs.get(index).copied().unwrap_or(false);
        for expanded in glob::expand_url(&raw, globoff)? {
            let effective_url =
                ipfs::maybe_rewrite_url(&expanded.url, transfer.ipfs_gateway.as_deref())?
                    .unwrap_or(expanded.url);
            let mut url =
                Url::parse(&effective_url).map_err(|error| CurlError::Url(error.to_string()))?;
            if matches!(url.scheme(), "http" | "https" | "ftp" | "sftp" | "tftp") {
                data::append_upload_filename_to_url(&mut url, transfer.upload_file.as_deref());
            }
            if let Some(query) = query.filter(|query| !query.is_empty()) {
                append_query_body(&mut url, &query.bytes);
            }
            if transfer.get
                && let Some(body) = body.filter(|body| !body.is_empty())
            {
                append_query_body(&mut url, &body.bytes);
            }
            urls.push(url.to_string());
        }
    }
    Ok(urls)
}

fn effective_headers(
    transfer: &TransferConfig,
    body: Option<&PreparedBody>,
) -> Result<Vec<String>> {
    let mut headers = transfer.headers.clone();
    let has_accept = headers
        .iter()
        .any(|header| header_name_is(header, "accept"));
    let has_content_type = headers
        .iter()
        .any(|header| header_name_is(header, "content-type"));

    if body.is_some_and(|body| body.is_json) {
        if !has_content_type {
            headers.push("Content-Type: application/json".to_string());
        }
        if !has_accept {
            headers.push("Accept: application/json".to_string());
        }
    }

    Ok(headers)
}

fn header_name_is(header: &str, expected: &str) -> bool {
    header
        .split_once(':')
        .is_some_and(|(name, _)| name.trim().eq_ignore_ascii_case(expected))
}

fn append_query_body(url: &mut Url, body: &[u8]) {
    let body = String::from_utf8_lossy(body);
    let mut query = url.query().unwrap_or("").to_string();
    if !query.is_empty() && !body.is_empty() {
        query.push('&');
    }
    query.push_str(&body);
    url.set_query(Some(&query));
}

fn emit_http_version(out: &mut String, version: HttpVersionPreference) {
    let value = match version {
        HttpVersionPreference::Any => return,
        HttpVersionPreference::Http10 => "CURL_HTTP_VERSION_1_0",
        HttpVersionPreference::Http11 => "CURL_HTTP_VERSION_1_1",
        HttpVersionPreference::Http2 => "CURL_HTTP_VERSION_2_0",
        HttpVersionPreference::Http2PriorKnowledge => "CURL_HTTP_VERSION_2_PRIOR_KNOWLEDGE",
    };
    emit_raw_setopt(out, "CURLOPT_HTTP_VERSION", value);
}

fn emit_ssl_version(out: &mut String, version: Option<SslVersionPreference>) {
    let value = match version {
        Some(SslVersionPreference::TlsV1_0) => "CURL_SSLVERSION_TLSv1_0",
        Some(SslVersionPreference::TlsV1_1) => "CURL_SSLVERSION_TLSv1_1",
        Some(SslVersionPreference::TlsV1_2) => "CURL_SSLVERSION_TLSv1_2",
        Some(SslVersionPreference::TlsV1_3) => "CURL_SSLVERSION_TLSv1_3",
        None => return,
    };
    emit_raw_setopt(out, "CURLOPT_SSLVERSION", value);
}

fn emit_ip_version(out: &mut String, version: IpVersionPreference) {
    let value = match version {
        IpVersionPreference::Any => return,
        IpVersionPreference::Ipv4 => "CURL_IPRESOLVE_V4",
        IpVersionPreference::Ipv6 => "CURL_IPRESOLVE_V6",
    };
    emit_raw_setopt(out, "CURLOPT_IPRESOLVE", value);
}

fn postredir_bitmask(transfer: &TransferConfig) -> i64 {
    let mut bitmask = 0;
    if transfer.post301 {
        bitmask |= 1;
    }
    if transfer.post302 {
        bitmask |= 2;
    }
    if transfer.post303 {
        bitmask |= 4;
    }
    bitmask
}

fn emit_slist_append(out: &mut String, slist: &str, value: &str) {
    writeln!(
        out,
        "  {slist} = curl_slist_append({slist}, \"{}\");",
        c_escape(value.as_bytes())
    )
    .unwrap();
}

fn write_slist_initializer(out: &mut String, slist: Option<&str>, values: &[String]) {
    let Some(slist) = slist else {
        return;
    };
    writeln!(out, "  {slist} = NULL;").unwrap();
    for value in values {
        emit_slist_append(out, slist, value);
    }
    out.push('\n');
}

fn emit_string_setopt(out: &mut String, option: &str, value: &str) {
    emit_bytes_setopt(out, option, value.as_bytes());
}

fn emit_path_setopt(out: &mut String, option: &str, value: &Path) {
    emit_bytes_setopt(out, option, value.to_string_lossy().as_bytes());
}

fn emit_bytes_setopt(out: &mut String, option: &str, value: &[u8]) {
    writeln!(
        out,
        "  curl_easy_setopt(curl, {option}, \"{}\");",
        c_escape(value)
    )
    .unwrap();
}

fn emit_long_setopt(out: &mut String, option: &str, value: i64) {
    emit_raw_setopt(out, option, &format!("{value}L"));
}

fn emit_raw_setopt(out: &mut String, option: &str, value: &str) {
    writeln!(out, "  curl_easy_setopt(curl, {option}, {value});").unwrap();
}

fn c_escape(bytes: &[u8]) -> String {
    let mut escaped = String::new();
    for &byte in bytes {
        match byte {
            b'\n' => escaped.push_str("\\n"),
            b'\r' => escaped.push_str("\\r"),
            b'\t' => escaped.push_str("\\t"),
            b'\\' => escaped.push_str("\\\\"),
            b'"' => escaped.push_str("\\\""),
            b'?' => escaped.push_str("\\?"),
            0x20..=0x7e => escaped.push(byte as char),
            other => write!(escaped, "\\{other:03o}").unwrap(),
        }
    }
    escaped
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cli::parse_args;

    #[test]
    fn renders_minimal_get_source() {
        let config = parse_args(["-q", "--libcurl", "client.c", "https://example.com"]).unwrap();

        let source = render_source(&config).unwrap();

        assert!(source.contains("Sample code generated by the curl command line tool"));
        assert!(source.contains("#include <curl/curl.h>"));
        assert!(source.contains("curl_easy_setopt(curl, CURLOPT_URL, \"https://example.com/\");"));
        assert!(source.contains("curl_easy_perform(curl);"));
        assert!(source.contains("curl_easy_cleanup(curl);"));
    }

    #[test]
    fn escapes_c_string_bytes() {
        assert_eq!(
            c_escape(b"quote\" slash\\ newline\n nul\0 ?"),
            "quote\\\" slash\\\\ newline\\n nul\\000 \\?"
        );
        assert_eq!(c_escape(&[0x80, b'a', 0xff]), "\\200a\\377");
    }

    #[test]
    fn renders_headers_data_auth_and_proxy_options() {
        let config = parse_args([
            "-q",
            "-H",
            "X-Test: yes",
            "-d",
            "a=b",
            "-u",
            "alice:secret",
            "-x",
            "http://proxy.example:8080",
            "--noproxy",
            "localhost",
            "-A",
            "MyUA",
            "https://example.com",
        ])
        .unwrap();

        let source = render_source(&config).unwrap();

        assert!(source.contains("struct curl_slist *slist1;"));
        assert!(source.contains("curl_slist_append(slist1, \"X-Test: yes\");"));
        assert!(source.contains("CURLOPT_HTTPHEADER, slist1"));
        assert!(source.contains("CURLOPT_POSTFIELDS, \"a=b\""));
        assert!(source.contains("CURLOPT_POSTFIELDSIZE_LARGE, (curl_off_t)3"));
        assert!(source.contains("CURLOPT_USERPWD, \"alice:secret\""));
        assert!(source.contains("CURLOPT_PROXY, \"http://proxy.example:8080\""));
        assert!(source.contains("CURLOPT_NOPROXY, \"localhost\""));
        assert!(source.contains("CURLOPT_USERAGENT, \"MyUA\""));
    }

    #[test]
    fn renders_auto_referer_without_initial_referer() {
        let config = parse_args([
            "-q",
            "--libcurl",
            "client.c",
            "-e",
            ";auto",
            "https://example.com",
        ])
        .unwrap();

        let source = render_source(&config).unwrap();

        assert!(source.contains("CURLOPT_AUTOREFERER, 1"));
        assert!(!source.contains("CURLOPT_REFERER"));
    }

    #[test]
    fn renders_post_redirect_options() {
        let config = parse_args([
            "-q",
            "--libcurl",
            "client.c",
            "--post301",
            "--post303",
            "https://example.com",
        ])
        .unwrap();

        let source = render_source(&config).unwrap();

        assert!(source.contains("CURLOPT_POSTREDIR, 5L"));
    }

    #[test]
    fn renders_resolve_options() {
        let config = parse_args([
            "-q",
            "--libcurl",
            "client.c",
            "--resolve",
            "example.com:443:127.0.0.1",
            "https://example.com",
        ])
        .unwrap();

        let source = render_source(&config).unwrap();

        assert!(source.contains("struct curl_slist *slist1;"));
        assert!(source.contains("curl_slist_append(slist1, \"example.com:443:127.0.0.1\");"));
        assert!(source.contains("CURLOPT_RESOLVE, slist1"));
        assert!(source.contains("curl_slist_free_all(slist1);"));
    }

    #[test]
    fn renders_connect_to_options() {
        let config = parse_args([
            "-q",
            "--libcurl",
            "client.c",
            "--connect-to",
            "example.com:443:127.0.0.1:8443",
            "https://example.com",
        ])
        .unwrap();

        let source = render_source(&config).unwrap();

        assert!(source.contains("struct curl_slist *slist1;"));
        assert!(source.contains("curl_slist_append(slist1, \"example.com:443:127.0.0.1:8443\");"));
        assert!(source.contains("CURLOPT_CONNECT_TO, slist1"));
        assert!(source.contains("curl_slist_free_all(slist1);"));
    }

    #[test]
    fn renders_disallow_username_in_url_option() {
        let config = parse_args([
            "-q",
            "--libcurl",
            "client.c",
            "--disallow-username-in-url",
            "https://example.com",
        ])
        .unwrap();

        let source = render_source(&config).unwrap();

        assert!(source.contains("CURLOPT_DISALLOW_USERNAME_IN_URL, 1L"));
    }

    #[test]
    fn renders_oauth2_bearer_option() {
        let config = parse_args([
            "-q",
            "--libcurl",
            "client.c",
            "--oauth2-bearer",
            "token123",
            "https://example.com",
        ])
        .unwrap();

        let source = render_source(&config).unwrap();

        assert!(source.contains("CURLOPT_XOAUTH2_BEARER, \"token123\""));
    }

    #[test]
    fn renders_get_data_as_query_and_expands_globs() {
        let config =
            parse_args(["-q", "-G", "-d", "a=b", "https://example.com/item[1-2]"]).unwrap();

        let source = render_source(&config).unwrap();

        assert!(source.contains("CURLOPT_URL, \"https://example.com/item1\\?a=b\""));
        assert!(source.contains("CURLOPT_URL, \"https://example.com/item2\\?a=b\""));
        assert!(!source.contains("CURLOPT_POSTFIELDS"));
    }
}
