use std::fmt::Write as _;
use std::io::Write as _;
use std::path::Path;

use url::Url;

use crate::cli::{Config, ContinueAt, HttpVersionPreference, TransferConfig};
use crate::data::{self, PreparedBody};
use crate::error::{CurlError, Result};
use crate::{glob, ipfs};

pub fn write_source(path: &Path, config: &Config) -> Result<()> {
    let source = render_source(config)?;
    if path == Path::new("-") {
        let mut stdout = std::io::stdout().lock();
        stdout.write_all(source.as_bytes())?;
    } else {
        std::fs::write(path, source)?;
    }
    Ok(())
}

fn render_source(config: &Config) -> Result<String> {
    let render_transfers = prepare_transfers(config)?;
    let mut out = String::new();

    write_header(&mut out);
    write_declarations(&mut out, &render_transfers);
    write_slist_initializers(&mut out, &render_transfers);

    writeln!(out, "  curl = curl_easy_init();").unwrap();

    let mut request_index = 0;
    for transfer in &render_transfers {
        for url in &transfer.urls {
            if request_index > 0 {
                writeln!(out, "  curl_easy_reset(curl);").unwrap();
            }
            write_request(&mut out, transfer, url)?;
            request_index += 1;
        }
    }

    write_unrepresentable_comment(&mut out);
    writeln!(out, "  curl_easy_cleanup(curl);").unwrap();
    writeln!(out, "  curl = NULL;").unwrap();
    write_cleanup(&mut out, &render_transfers);
    out.push('\n');
    writeln!(out, "  return (int)result;").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out, "/**** End of sample code ****/").unwrap();

    Ok(out)
}

struct RenderTransfer<'a> {
    transfer: &'a TransferConfig,
    urls: Vec<String>,
    body: Option<PreparedBody>,
    headers: Vec<String>,
    slist: Option<String>,
    mail_rcpt_slist: Option<String>,
}

fn prepare_transfers(config: &Config) -> Result<Vec<RenderTransfer<'_>>> {
    let mut slist_index = 1;
    let mut transfers = Vec::new();

    for transfer in &config.transfers {
        let query = data::prepare_body(&transfer.url_query)?;
        let body = data::prepare_body(&transfer.data)?;
        let urls = effective_urls(transfer, query.as_ref(), body.as_ref())?;
        let headers = effective_headers(transfer, body.as_ref())?;
        let slist = if headers.is_empty() {
            None
        } else {
            let name = format!("slist{slist_index}");
            slist_index += 1;
            Some(name)
        };
        let mail_rcpt_slist = if transfer.mail_rcpt.is_empty() {
            None
        } else {
            let name = format!("slist{slist_index}");
            slist_index += 1;
            Some(name)
        };

        transfers.push(RenderTransfer {
            transfer,
            urls,
            body,
            headers,
            slist,
            mail_rcpt_slist,
        });
    }

    Ok(transfers)
}

fn write_header(out: &mut String) {
    out.push_str(
        "/********* Sample code generated by the curl command line tool **********\n\
 * All curl_easy_setopt() options are documented at:\n\
 * https://curl.se/libcurl/c/curl_easy_setopt.html\n\
 ************************************************************************/\n\
#include <curl/curl.h>\n\n\
int main(int argc, char *argv[])\n\
{\n\
  CURLcode result;\n\
  CURL *curl;\n",
    );
}

fn write_declarations(out: &mut String, transfers: &[RenderTransfer<'_>]) {
    for transfer in transfers {
        if let Some(slist) = &transfer.slist {
            writeln!(out, "  struct curl_slist *{slist};").unwrap();
        }
        if let Some(slist) = &transfer.mail_rcpt_slist {
            writeln!(out, "  struct curl_slist *{slist};").unwrap();
        }
    }
    out.push('\n');
}

fn write_slist_initializers(out: &mut String, transfers: &[RenderTransfer<'_>]) {
    for transfer in transfers {
        let Some(slist) = &transfer.slist else {
            if let Some(slist) = &transfer.mail_rcpt_slist {
                writeln!(out, "  {slist} = NULL;").unwrap();
                for recipient in &transfer.transfer.mail_rcpt {
                    emit_slist_append(out, slist, recipient);
                }
                out.push('\n');
            }
            continue;
        };
        writeln!(out, "  {slist} = NULL;").unwrap();
        for header in &transfer.headers {
            emit_slist_append(out, slist, header);
        }
        out.push('\n');
        if let Some(slist) = &transfer.mail_rcpt_slist {
            writeln!(out, "  {slist} = NULL;").unwrap();
            for recipient in &transfer.transfer.mail_rcpt {
                emit_slist_append(out, slist, recipient);
            }
            out.push('\n');
        }
    }
}

fn write_request(out: &mut String, render: &RenderTransfer<'_>, url: &str) -> Result<()> {
    let transfer = render.transfer;
    emit_long_setopt(out, "CURLOPT_VERBOSE", 1);
    emit_long_setopt(out, "CURLOPT_BUFFERSIZE", 102400);
    emit_string_setopt(out, "CURLOPT_URL", url);

    if let Some(method) = &transfer.method {
        emit_string_setopt(out, "CURLOPT_CUSTOMREQUEST", method);
    }
    if transfer.head {
        emit_long_setopt(out, "CURLOPT_NOBODY", 1);
    }
    if transfer.include_headers {
        emit_long_setopt(out, "CURLOPT_HEADER", 1);
    }
    if transfer.list_only {
        emit_long_setopt(out, "CURLOPT_DIRLISTONLY", 1);
    }
    if transfer.fail {
        emit_long_setopt(out, "CURLOPT_FAILONERROR", 1);
    }
    if let Some(slist) = &render.slist {
        emit_raw_setopt(out, "CURLOPT_HTTPHEADER", slist);
    }
    if let Some(mail_from) = &transfer.mail_from {
        emit_string_setopt(out, "CURLOPT_MAIL_FROM", mail_from);
    }
    if let Some(slist) = &render.mail_rcpt_slist {
        emit_raw_setopt(out, "CURLOPT_MAIL_RCPT", slist);
    }
    if transfer.mail_rcpt_allowfails {
        emit_long_setopt(out, "CURLOPT_MAIL_RCPT_ALLOWFAILS", 1);
    }
    if let Some(body) = &render.body
        && !transfer.get
    {
        emit_bytes_setopt(out, "CURLOPT_POSTFIELDS", &body.bytes);
        emit_raw_setopt(
            out,
            "CURLOPT_POSTFIELDSIZE_LARGE",
            &format!("(curl_off_t){}", body.bytes.len()),
        );
    }
    if let Some(upload_file) = &transfer.upload_file {
        emit_long_setopt(out, "CURLOPT_UPLOAD", 1);
        if upload_file != "-"
            && let Ok(metadata) = std::fs::metadata(upload_file)
            && metadata.is_file()
        {
            emit_raw_setopt(
                out,
                "CURLOPT_INFILESIZE_LARGE",
                &format!("(curl_off_t){}", metadata.len()),
            );
        }
        writeln!(
            out,
            "  /* Upload source wiring is not yet represented by this Rust --libcurl slice. */"
        )
        .unwrap();
    }
    if !transfer.forms.is_empty() {
        writeln!(
            out,
            "  /* Multipart form generation is not yet represented by this Rust --libcurl slice. */"
        )
        .unwrap();
    }
    if let Some(user) = &transfer.user {
        emit_string_setopt(out, "CURLOPT_USERPWD", user);
        emit_raw_setopt(out, "CURLOPT_HTTPAUTH", "(long)CURLAUTH_BASIC");
    }
    if let Some(token) = &transfer.oauth2_bearer {
        emit_string_setopt(out, "CURLOPT_XOAUTH2_BEARER", token);
    }
    if let Some(proxy) = &transfer.proxy {
        emit_string_setopt(out, "CURLOPT_PROXY", proxy);
    }
    if let Some(proxy_user) = &transfer.proxy_user {
        emit_string_setopt(out, "CURLOPT_PROXYUSERPWD", proxy_user);
    }
    if let Some(noproxy) = &transfer.noproxy {
        emit_string_setopt(out, "CURLOPT_NOPROXY", noproxy);
    }
    if transfer.insecure {
        emit_long_setopt(out, "CURLOPT_SSL_VERIFYPEER", 0);
        emit_long_setopt(out, "CURLOPT_SSL_VERIFYHOST", 0);
    }
    if let Some(timeout) = transfer.connect_timeout {
        emit_raw_setopt(
            out,
            "CURLOPT_CONNECTTIMEOUT_MS",
            &format!("{}L", timeout.as_millis()),
        );
    }
    if let Some(timeout) = transfer.max_time {
        emit_raw_setopt(
            out,
            "CURLOPT_TIMEOUT_MS",
            &format!("{}L", timeout.as_millis()),
        );
    }
    if let Some(max_filesize) = transfer.max_filesize {
        emit_raw_setopt(
            out,
            "CURLOPT_MAXFILESIZE_LARGE",
            &format!("(curl_off_t){max_filesize}"),
        );
    }
    if let Some(referer) = &transfer.referer {
        emit_string_setopt(out, "CURLOPT_REFERER", referer);
    }
    if transfer.auto_referer {
        emit_long_setopt(out, "CURLOPT_AUTOREFERER", 1);
    }
    if let Some(range) = &transfer.range {
        emit_string_setopt(out, "CURLOPT_RANGE", range);
    }
    if let Some(continue_at) = transfer.continue_at {
        match continue_at {
            ContinueAt::Offset(offset) => emit_raw_setopt(
                out,
                "CURLOPT_RESUME_FROM_LARGE",
                &format!("(curl_off_t){offset}"),
            ),
            ContinueAt::Auto => writeln!(
                out,
                "  /* --continue-at - depends on the selected output file size at runtime. */"
            )
            .unwrap(),
        }
    }
    if transfer.follow_location {
        emit_long_setopt(out, "CURLOPT_FOLLOWLOCATION", 1);
    }
    emit_long_setopt(out, "CURLOPT_MAXREDIRS", transfer.max_redirs as i64);
    if let Some(cookie) = &transfer.cookie {
        emit_string_setopt(out, "CURLOPT_COOKIE", cookie);
    }
    for cookie_file in &transfer.cookie_files {
        emit_string_setopt(out, "CURLOPT_COOKIEFILE", cookie_file);
    }
    if let Some(cookie_jar) = &transfer.cookie_jar {
        emit_string_setopt(out, "CURLOPT_COOKIEJAR", &cookie_jar.to_string_lossy());
    }
    if transfer.junk_session_cookies {
        emit_long_setopt(out, "CURLOPT_COOKIESESSION", 1);
    }
    if transfer.compressed {
        emit_string_setopt(out, "CURLOPT_ACCEPT_ENCODING", "");
    }
    if let Some(user_agent) = &transfer.user_agent {
        emit_string_setopt(out, "CURLOPT_USERAGENT", user_agent);
    } else {
        emit_string_setopt(
            out,
            "CURLOPT_USERAGENT",
            concat!("curl-rust/", env!("CARGO_PKG_VERSION")),
        );
    }
    emit_http_version(out, transfer.http_version);
    emit_long_setopt(out, "CURLOPT_TCP_KEEPALIVE", 1);
    out.push('\n');
    writeln!(out, "  result = curl_easy_perform(curl);").unwrap();
    out.push('\n');
    Ok(())
}

fn write_unrepresentable_comment(out: &mut String) {
    out.push_str(
        "  /* Here is a list of options the curl code used that cannot get generated\n\
     as source easily. You may choose to either not use them or implement\n\
     them yourself.\n\n\
  CURLOPT_WRITEDATA was set to an object pointer\n\
  CURLOPT_WRITEFUNCTION was set to a function pointer\n\
  CURLOPT_HEADERFUNCTION was set to a function pointer\n\
  CURLOPT_HEADERDATA was set to an object pointer\n\
  CURLOPT_ERRORBUFFER was set to an object pointer\n\n\
  */\n\n",
    );
}

fn write_cleanup(out: &mut String, transfers: &[RenderTransfer<'_>]) {
    for transfer in transfers {
        if let Some(slist) = &transfer.slist {
            writeln!(out, "  curl_slist_free_all({slist});").unwrap();
            writeln!(out, "  {slist} = NULL;").unwrap();
        }
        if let Some(slist) = &transfer.mail_rcpt_slist {
            writeln!(out, "  curl_slist_free_all({slist});").unwrap();
            writeln!(out, "  {slist} = NULL;").unwrap();
        }
    }
}

fn effective_urls(
    transfer: &TransferConfig,
    query: Option<&PreparedBody>,
    body: Option<&PreparedBody>,
) -> Result<Vec<String>> {
    let mut urls = Vec::new();
    for raw in &transfer.urls {
        for expanded in glob::expand_url(raw, transfer.globoff)? {
            let effective_url =
                ipfs::maybe_rewrite_url(&expanded.url, transfer.ipfs_gateway.as_deref())?
                    .unwrap_or(expanded.url);
            let mut url =
                Url::parse(&effective_url).map_err(|error| CurlError::Url(error.to_string()))?;
            if matches!(url.scheme(), "http" | "https") {
                data::append_upload_filename_to_url(&mut url, transfer.upload_file.as_deref());
            }
            if let Some(query) = query.filter(|query| !query.is_empty()) {
                append_query_body(&mut url, &query.bytes);
            }
            if transfer.get
                && let Some(body) = body.filter(|body| !body.is_empty())
            {
                append_query_body(&mut url, &body.bytes);
            }
            urls.push(url.to_string());
        }
    }
    Ok(urls)
}

fn effective_headers(
    transfer: &TransferConfig,
    body: Option<&PreparedBody>,
) -> Result<Vec<String>> {
    let mut headers = expand_header_arguments(&transfer.headers)?;
    let has_accept = headers
        .iter()
        .any(|header| header_name_is(header, "accept"));
    let has_content_type = headers
        .iter()
        .any(|header| header_name_is(header, "content-type"));

    if body.is_some_and(|body| body.is_json) {
        if !has_content_type {
            headers.push("Content-Type: application/json".to_string());
        }
        if !has_accept {
            headers.push("Accept: application/json".to_string());
        }
    }

    Ok(headers)
}

fn expand_header_arguments(headers: &[String]) -> Result<Vec<String>> {
    let mut expanded = Vec::new();
    for header in headers {
        if let Some(path) = header.strip_prefix('@') {
            let text = std::fs::read_to_string(path)?;
            expanded.extend(
                text.lines()
                    .map(str::trim)
                    .filter(|line| !line.is_empty())
                    .map(ToString::to_string),
            );
        } else {
            expanded.push(header.clone());
        }
    }
    Ok(expanded)
}

fn header_name_is(header: &str, expected: &str) -> bool {
    header
        .split_once(':')
        .is_some_and(|(name, _)| name.trim().eq_ignore_ascii_case(expected))
}

fn append_query_body(url: &mut Url, body: &[u8]) {
    let body = String::from_utf8_lossy(body);
    let mut query = url.query().unwrap_or("").to_string();
    if !query.is_empty() && !body.is_empty() {
        query.push('&');
    }
    query.push_str(&body);
    url.set_query(Some(&query));
}

fn emit_http_version(out: &mut String, version: HttpVersionPreference) {
    let value = match version {
        HttpVersionPreference::Any => return,
        HttpVersionPreference::Http10 => "CURL_HTTP_VERSION_1_0",
        HttpVersionPreference::Http11 => "CURL_HTTP_VERSION_1_1",
        HttpVersionPreference::Http2 => "CURL_HTTP_VERSION_2_0",
        HttpVersionPreference::Http2PriorKnowledge => "CURL_HTTP_VERSION_2_PRIOR_KNOWLEDGE",
    };
    emit_raw_setopt(out, "CURLOPT_HTTP_VERSION", value);
}

fn emit_slist_append(out: &mut String, slist: &str, value: &str) {
    writeln!(
        out,
        "  {slist} = curl_slist_append({slist}, \"{}\");",
        c_escape(value.as_bytes())
    )
    .unwrap();
}

fn emit_string_setopt(out: &mut String, option: &str, value: &str) {
    emit_bytes_setopt(out, option, value.as_bytes());
}

fn emit_bytes_setopt(out: &mut String, option: &str, value: &[u8]) {
    writeln!(
        out,
        "  curl_easy_setopt(curl, {option}, \"{}\");",
        c_escape(value)
    )
    .unwrap();
}

fn emit_long_setopt(out: &mut String, option: &str, value: i64) {
    emit_raw_setopt(out, option, &format!("{value}L"));
}

fn emit_raw_setopt(out: &mut String, option: &str, value: &str) {
    writeln!(out, "  curl_easy_setopt(curl, {option}, {value});").unwrap();
}

fn c_escape(bytes: &[u8]) -> String {
    let mut escaped = String::new();
    for &byte in bytes {
        match byte {
            b'\n' => escaped.push_str("\\n"),
            b'\r' => escaped.push_str("\\r"),
            b'\t' => escaped.push_str("\\t"),
            b'\\' => escaped.push_str("\\\\"),
            b'"' => escaped.push_str("\\\""),
            b'?' => escaped.push_str("\\?"),
            0x20..=0x7e => escaped.push(byte as char),
            other => write!(escaped, "\\{other:03o}").unwrap(),
        }
    }
    escaped
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cli::parse_args;

    #[test]
    fn renders_minimal_get_source() {
        let config = parse_args(["-q", "--libcurl", "client.c", "https://example.com"]).unwrap();

        let source = render_source(&config).unwrap();

        assert!(source.contains("Sample code generated by the curl command line tool"));
        assert!(source.contains("#include <curl/curl.h>"));
        assert!(source.contains("curl_easy_setopt(curl, CURLOPT_URL, \"https://example.com/\");"));
        assert!(source.contains("curl_easy_perform(curl);"));
        assert!(source.contains("curl_easy_cleanup(curl);"));
    }

    #[test]
    fn escapes_c_string_bytes() {
        assert_eq!(
            c_escape(b"quote\" slash\\ newline\n nul\0 ?"),
            "quote\\\" slash\\\\ newline\\n nul\\000 \\?"
        );
        assert_eq!(c_escape(&[0x80, b'a', 0xff]), "\\200a\\377");
    }

    #[test]
    fn renders_headers_data_auth_and_proxy_options() {
        let config = parse_args([
            "-q",
            "-H",
            "X-Test: yes",
            "-d",
            "a=b",
            "-u",
            "alice:secret",
            "-x",
            "http://proxy.example:8080",
            "--noproxy",
            "localhost",
            "-A",
            "MyUA",
            "https://example.com",
        ])
        .unwrap();

        let source = render_source(&config).unwrap();

        assert!(source.contains("struct curl_slist *slist1;"));
        assert!(source.contains("curl_slist_append(slist1, \"X-Test: yes\");"));
        assert!(source.contains("CURLOPT_HTTPHEADER, slist1"));
        assert!(source.contains("CURLOPT_POSTFIELDS, \"a=b\""));
        assert!(source.contains("CURLOPT_POSTFIELDSIZE_LARGE, (curl_off_t)3"));
        assert!(source.contains("CURLOPT_USERPWD, \"alice:secret\""));
        assert!(source.contains("CURLOPT_PROXY, \"http://proxy.example:8080\""));
        assert!(source.contains("CURLOPT_NOPROXY, \"localhost\""));
        assert!(source.contains("CURLOPT_USERAGENT, \"MyUA\""));
    }

    #[test]
    fn renders_auto_referer_without_initial_referer() {
        let config = parse_args([
            "-q",
            "--libcurl",
            "client.c",
            "-e",
            ";auto",
            "https://example.com",
        ])
        .unwrap();

        let source = render_source(&config).unwrap();

        assert!(source.contains("CURLOPT_AUTOREFERER, 1"));
        assert!(!source.contains("CURLOPT_REFERER"));
    }

    #[test]
    fn renders_get_data_as_query_and_expands_globs() {
        let config =
            parse_args(["-q", "-G", "-d", "a=b", "https://example.com/item[1-2]"]).unwrap();

        let source = render_source(&config).unwrap();

        assert!(source.contains("CURLOPT_URL, \"https://example.com/item1\\?a=b\""));
        assert!(source.contains("CURLOPT_URL, \"https://example.com/item2\\?a=b\""));
        assert!(!source.contains("CURLOPT_POSTFIELDS"));
    }
}
